alias nb="npm run build"
alias nd="npm run deploy"
alias nw="npm run watch"
alias ns="npm run start"
alias no="npm run open"
alias nfi="npm run framework-init"
alias nfu="npm run framework-update"
alias nls="npm ls --depth=0"
