alias nb="npm run build"
alias nd="npm run deploy"
alias ndp="npm run deploy-preview"
alias ni="npm install"
alias nls="npm ls --depth=0"
alias no="npm run open"
alias ns="npm run start"
alias nw="npm run watch"
