alias nb="npm run build"
alias nd="npm run deploy"
alias ndp="npm run deploy-preview"
alias ni="npm install"
alias nl="npm run login"
alias nls="npm ls --depth=0"
alias npl="npm run pull"
alias nps="npm run push"
alias npsa="npm run push-all"
alias no="npm run open"
alias ns="npm run start"
alias nsw="npm run start-ws"
alias nw="npm run watch"

alias nxpj="npx theme pull-json"
alias nxu="npx theme update latest"
